export const actionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_TODOLIST: "UPDATE_TODOLIST",
  CHANGE_INPUT: "CHANGE_INPUT",
  CHANGE_EMAIL: "CHANGE_EMAIL",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  LOADING: "LOADING",
  ERROR: "ERROR"
};
